spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pizzadelivery
    username: postgres
    password: postgres

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger

logging:
  pattern:
    console: "%white(%d{ISO8601}) %highlight(%-5level) [%blue(%t{20})] %yellow(%C{40}): %msg%n%throwable"
  level:
    org.example.PizzaDeliveryApplication: DEBUG

security:
  disabled:
    paths: "/swagger**,/auth/login,/auth/register,/v3/api-docs**,/pizza"

